#!/bin/bash

#PBS -l walltime=20:00:00,nodes=1:ppn=1
#PBS -joe .
#PBS -d .
#PBS -l vmem=20g,mem=20g

CRT_HOME='/home/naumenko/crt'

if [ -z "$transcript_file" ];
then
	transcript_file=$CRT_HOME/all-protein-coding-genes-no-patches.list
fi

if [ -z "$processes" ];
then
	processes=1
fi

if [ -z "$bam_list" ];
then
	bam_list=bamlist.txt
fi

module load python/3.5.2
python3 $CRT_HOME/SpliceJunctionDiscovery.py -transcript_file=$transcript_file -bam_list=$bam_list -processes=$processes

echo "done"