#!/bin/bash

#PBS -l walltime=20:00:00,nodes=1:ppn=10
#PBS -joe .
#PBS -d .
#PBS -l vmem=20g,mem=20g

MENDELIAN_RNA_SEQ_DB_HOME='/hpf/largeprojects/ccmbio/naumenko/tools/MendelianRNA-seq-DB'

if [ -z "$transcript_file" ];
then
	transcript_file=$MENDELIAN_RNA_SEQ_DB_HOME/all-protein-coding-genes-no-patches.list
fi

if [ -z "$processes" ];
then
	processes=10
fi

if [ -z "$bam_list" ];
then
	bam_list=bamlist.txt
fi

module load python/3.5.2
python3 $MENDELIAN_RNA_SEQ_DB_HOME/analysis/SpliceJunctionDiscovery.py -transcript_file=$transcript_file -bam_list=$bam_list -processes=$processes
