#!/bin/bash

#PBS -l walltime=20:00:00,nodes=1:ppn=10
#PBS -joe .
#PBS -d .
#PBS -l vmem=20g,mem=20g

MENDELIAN_RNA_SEQ_DB_HOME='/hpf/largeprojects/ccmbio/naumenko/tools/MendelianRNA-seq-DB'

transcript_file=$MENDELIAN_RNA_SEQ_DB_HOME/all-protein-coding-genes-no-patches.list
processes=10
bam_list=bamlist.txt

ls *.bam > bamlist.txt

module load python/3.5.2
python3 $MENDELIAN_RNA_SEQ_DB_HOME/analysis/SpliceJunctionDiscovery.py -transcript_file=$transcript_file -bam_list=$bam_list -processes=$processes

/hpf/largeprojects/ccmbio/naumenko/project_RNAseq_diagnostics/controls/30controls.junctions.db SpliceJunctions.db

#because something goes wrong with many threads
processes=4
python3 $MENDELIAN_RNA_SEQ_DB_HOME/analysis/AddJunctionsToDatabase.py \
	--addBAM \
	-transcript_file=$transcript_file \
	-processes=$processes \
	-bamlist=$bam_list \
	-flank=1

