#!/bin/bash

#PBS -l walltime=20:00:00,nodes=1:ppn=1
#PBS -joe .
#PBS -d .
#PBS -l vmem=10g,mem=10g

CRT_HOME='/home/naumenko/crt'

cp $bam.junctions.txt /localhd/$PBS_JOBID
#cp /hpf/largeprojects/ccmbio/naumenko/project_RNAseq_diagnostics/controls/muscle/cp-SpliceJunction.db.transcript_junctions_only /localhd/$PBS_JOBID/SpliceJunction.db
cp SpliceJunction.db /localhd/$PBS_JOBID

cd /localhd/$PBS_JOBID

module load python/3.5.2
module load sqlite/3.20.0
python3 $CRT_HOME/AddJunctionsToDatabase.py \
	--addBAM \
	-bam=$bam
cd -
#overwrite previous SpliceJunction.db
cp /localhd/$PBS_JOBID/SpliceJunction.db .
