---
title: "DS example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ExperimentHub)
library(tidyverse)
library(magrittr)
library(Matrix)
library(reshape2)
library(S4Vectors)


library(ComplexHeatmap)
library(pheatmap)
library(scales)
library(scater)
library(Matrix.utils)
library(data.table)
library(edgeR)
library(limma)
library(UpSetR)
```

- http://biocworkshops2019.bioconductor.org.s3-website-us-east-1.amazonaws.com/page/muscWorkshop__vignette/

# Loading data

```{r}
eh <- ExperimentHub()
query(eh, "Kang")
sce <- eh[["EH2259"]]
sce <- sce[, sce$multiplets == "singlet" & !is.na(sce$cell)]
dim(sce)

colData(sce) %>% 
    as.data.frame %>% 
    transmute(
        group_id = stim, 
        patient_id = ind,
        sample_id = paste0(stim, ind),
        cluster_id = cell) %>%
    mutate_all(as.factor) %>% 
    set_rownames(colnames(sce)) %>% 
    DataFrame -> colData(sce)

head(colData(sce))

nk <- length(kids <- purrr::set_names(levels(sce$cluster_id)))
ns <- length(sids <- purrr::set_names(levels(sce$sample_id)))


m <- match(sids, sce$sample_id)
n_cells <- as.numeric(table(sce$sample_id))
ei <- data.frame(colData(sce)[m, ], 
    n_cells, row.names = NULL) %>% 
    select(-"cluster_id")


```

#Preprocessing
```{r}
sce[rowSums(counts(sce) > 0) > 0, ]
# calculate quality control (QC) metrics
sce <- calculateQCMetrics(sce)

# get cells w/ few/many detected genes
sce$is_outlier <- isOutlier(
    metric = sce$total_features_by_counts,
    nmads = 2, type = "both", log = TRUE)

# remove outlier cells
sce <- sce[, !sce$is_outlier]
dim(sce)

sce <- sce[rowSums(counts(sce) > 1) >= 10, ]

sizeFactors(sce) <- librarySizeFactors(sce)
sce <- normalize(sce)
assayNames(sce)
range(logcounts(sce))
```

# DS analysis
```{r}
# aggregate by cluster-sample
groups <- colData(sce)[, c("cluster_id", "sample_id")]
pb <- aggregate.Matrix(t(counts(sce)), 
      groupings = groups, fun = "sum") 

# split by cluster, transform & rename columns
pb <- split.data.frame(pb, rep(kids, ns)) %>% 
        lapply(function(u) set_colnames(t(u), unname(sids)))

# construct SCE of pseudo-bulk counts
# (assays = clusters, rows = genes, columns = samples)
pb <- SingleCellExperiment(assays = pb)

# split cell by cluster-sample
cs_by_ks <- as.data.frame(colData(sce)) %>% 
    rownames_to_column("cells") %>% setDT %>% 
        split(flatten = FALSE, sorted = TRUE,
            by = c("cluster_id", "sample_id")) %>% 
        map_depth(2, "cells")
    
# for ea. cluster-sample..
pb2 <- map_depth(cs_by_ks, 2, function(cs)
        rowSums(counts(sce[, cs]))) %>% # ..compute pseudobulks
        map(data.frame) # column-bind samples
```

# Pseudobulk level MDS plot
```{r}
# compute MDS coordinates
mds <- as.list(assays(pb)) %>% 
    lapply(as.data.frame.matrix) %>% 
    bind_cols %>% 
    DGEList(remove.zeros = TRUE) %>% 
    calcNormFactors %>% 
    plotMDS.DGEList(plot = FALSE)
    
# prep. data.frame for plotting
gg_df <- data.frame(mds[c("x", "y")],
    cluster_id = rep(kids, each = ns),
    sample_id = rep(sids, nk),
    group_id = ei$group_id[match(sids, ei$sample_id)])

ggplot(gg_df, aes(x, y, col = cluster_id, shape = group_id)) + 
    geom_point(size = 3, alpha = 0.8) +
    labs(x = "MDS dim. 1", y = "MDS dim. 2") + 
    theme(panel.grid.minor = element_blank()) +
    coord_fixed() + theme_bw()
```

# Cluster-sample cell-counts
```{r}
options(width = 100)
table(sce$cluster_id, sce$sample_id)
```

# Testing for DS
```{r}
design <- model.matrix(~ 0 + ei$group_id) %>% 
    set_rownames(ei$sample_id) %>% 
    set_colnames(levels(ei$group_id))    
contrast <- makeContrasts("stim-ctrl", levels = design)

res <- lapply(kids, function(k) {
    y <- assays(pb)[[k]]
    y <- DGEList(y, remove.zeros = TRUE)
    y <- calcNormFactors(y)
    y <- estimateDisp(y, design)
    fit <- glmQLFit(y, design)
    fit <- glmQLFTest(fit, contrast = contrast)
    topTags(fit, n = Inf, sort.by = "none")$table %>% 
        dplyr::mutate(gene = rownames(.), cluster_id = k) %>% 
        dplyr::rename(p_val = PValue, p_adj = FDR)
})

```
# Results filtering and overview
```{r}
# filter FDR < 0.05, |logFC| > 1 & sort by FDR
res_fil <- lapply(res, 
    function(u)  u %>% 
        dplyr::filter(p_adj < 0.05, abs(logFC) > 1) %>% 
        dplyr::arrange(p_adj))

# nb. & % of DE genes per cluster
n_de <- vapply(res_fil, nrow, numeric(1))
cbind(n_de, p_gs = n_de / nrow(sce) * 100)
```

# Between cluster concordance
```{r}
upset(fromList(map(res_fil, "gene")))
```

# Visualization

## Dimension reduction
```{r}
# t-SNE colored by cluster ID
plotReducedDim(sce, use_dimred = "TSNE", 
    colour_by = "cluster_id", point_size = 0.8, point_alpha = 0.4) + 
    guides(fill = guide_legend(override.aes = list(alpha = 1, size = 5)))

# t-SNE colored by group ID
plotReducedDim(sce, use_dimred = "TSNE", 
    colour_by = "group_id", point_size = 0.8, point_alpha = 0.4) + 
    guides(fill = guide_legend(override.aes = list(alpha = 1, size = 5)))
```

```{r}
sce <- runUMAP(sce)
plotReducedDim(sce, use_dimred = "UMAP")
```

## Cell level visualization
```{r}
# pull top-n genes for ea. cluster
top_gs <- lapply(res_fil, function(u) u$gene[seq_len(9)])

# split cells by cluster
cs_by_k <- split(colnames(sce), sce$cluster_id)

lapply(kids, function(k) {
    gs <- top_gs[[k]]  # get top gene-hits for cluster k
    cs <- cs_by_k[[k]] # subset cells assigned to cluster k
    plotExpression(sce[, cs], features = gs, 
        x = "sample_id", colour_by = "group_id", ncol = 3) +
        guides(fill = guide_legend(override.aes = list(size = 5, alpha = 1))) +
        theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

```

## Sample level visualization
```{r}
# calculate expression-means by cluster-sample
ms <- aggregate.Matrix(t(logcounts(sce)), 
    groupings = groups, fun = "mean") %>% 
    split.data.frame(rep(kids, ns)) %>% 
    lapply(function(u) set_colnames(t(u), unname(sids))) %>% 
    SingleCellExperiment(assays = .)

.z_norm <- function(x, th = 2.5) {
    x <- as.matrix(x)
    sds <- rowSds(x, na.rm = TRUE)
    sds[sds == 0] <- 1
    x <- t(t(x - rowMeans(x, na.rm = TRUE)) / sds)
    #x <- (x - rowMeans(x, na.rm = TRUE)) / sds
    x[x >  th] <-  th
    x[x < -th] <- -th
    return(x)
}

.plot_diff_hm <- function(ms, k, gs, ei) {
    mat <- assays(ms)[[k]][gs, ]
    m <- match(colnames(mat), ei$sample_id)
    cols <- hue_pal()(nlevels(ei$group_id))
    names(cols) <- levels(ei$group_id)
    col_anno <- columnAnnotation(
        df = data.frame(group_id = ei$group_id[m]),
        col = list(group_id = cols),
        gp = gpar(col = "white"),
        show_annotation_name = FALSE)
    Heatmap(.z_norm(mat), 
        column_title = k,
        name = "z-normalized\nexpression",
        col = c("royalblue", "cornflowerblue", "white", "gold", "orange"),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        row_names_side = "left",
        rect_gp = gpar(col = "white"),
        top_annotation = col_anno)
}

lapply(kids, function(k) {
    top20 <- res_fil[[k]]$gene[seq_len(20)] # subset top-20 hits for cluster k
    .plot_diff_hm(ms, k, top20, ei)         # render differential heatmap
})

```

# Differential abundance (DA) analysis
```{r}
# calculate cluster-sample cell counts
n_cells <- table(sce$cluster_id, sce$sample_id)

# calculate cluster proportions across samples
freqs <- prop.table(n_cells, margin = 1)
```

```{r}
# prep. data.frame for plotting
df <- data.frame(
    frequency = as.numeric(freqs), 
    cluster_id = rep(kids, ns),
    sample_id = rep(sids, each = nk))
m <- match(df$sample_id, ei$sample_id)
df$group_id <- ei$group_id[m]


# barplot of relative cluster-abundances
ggplot(df, aes(x = sample_id, y = frequency, fill = cluster_id)) +
    geom_bar(stat = "identity", position = "fill") + 
    facet_wrap(~ group_id, scales = "free_x") +
    theme_classic()  + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}
# boxplot of relative cluster-abundances
ggplot(df, aes(x = group_id, y = frequency, color = group_id)) +
    geom_boxplot(outlier.colour = NA) +  geom_jitter() +
    facet_wrap(~ cluster_id, scales = "free_y", ncol = 4) +
    theme_classic()
```

# Testing for DA
```{r}
y <- DGEList(counts = n_cells)
y <- estimateDisp(y, design, trend.method = "none")
fit <- glmFit(y, design)
fit <- glmLRT(fit, contrast = contrast)
topTags(fit, n = Inf)$table %>% round(2)
```