---
title: "Plot RNA velocity picture"
author: "Sergey Naumenko"
date: "`r Sys.Date()`"
output:
    html_document:
        code_folding: hide
        df_print: paged
        highlight: tango
        theme: default
        number_sections: true
        toc: true
        toc_float:
            collapsed: true
            smooth_scroll: false
params:
    variable_features: 3000
    npcs: 30
    sample: N6_3_4
---


```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(BUSpaRse)
library(Seurat)
library(SeuratWrappers)
library(velocyto.R)
library(scales)
library(plotly)

ggplot2::theme_set(theme_light(base_size = 14))

opts_chunk[["set"]](
    cache = FALSE,
    dev = c("png", "pdf"),
    error = TRUE,
    highlight = TRUE,
    message = FALSE,
    prompt = FALSE,
    tidy = FALSE,
    warning = FALSE)
```

# Overview
- needs 50G RAM

```{r}
seurat_velocity_file <- paste0("data/velocity/seurat.velocity.RDS")
if (file.exists(seurat_velocity_file)){
    seurat <- readRDS(seurat_velocity_file)
}else{
    seurat <- RunVelocity(seurat, 
                      ncores = 5, 
                      reduction = "pca", 
                      verbose = TRUE)    
    saveRDS(seurat, seurat_velocity_file)  
}
```

```{r}
cell_pal <- function(cell_cats, pal_fun) {
  categories <- sort(unique(cell_cats))
  pal <- setNames(pal_fun(length(categories)), categories)
  pal[cell_cats]
}

label_clusters <- function(labels, coords, ...) {
  df <- tibble(label = labels, x = coords[,1], y = coords[,2])
  df <- df %>% 
    group_by(label) %>% 
    summarize(x = median(x), y = median(y))
  text(df$x, df$y, df$label, ...)
}
```

```{r, fig.width = 10, fig.keep = "all", echo = TRUE}
cell_colors <- cell_pal(seurat$orig.ident, brewer_pal("qual", "Set2"))
cell_colors_clust <- cell_pal(seurat$seurat_clusters, hue_pal())
names(cell_colors) <- names(cell_colors_clust) <- Cells(seurat)

cc_umap <- show.velocity.on.embedding.cor(emb = Embeddings(seurat, "umap"),
                                          vel = Tool(seurat, slot = "RunVelocity"),
                                          n.cores = 10, 
                                          show.grid.flow = TRUE,
                                          grid.n = 50, 
                                          cell.colors = cell_colors,
                                          cex = 0.5, 
                                          cell.border.alpha = 0,
                                          arrow.scale = 2, 
                                          arrow.lwd = 0.6,
                                          xlab = "UMAP1", 
                                          ylab = "UMAP2")
  
label_clusters(seurat$seurat_clusters, Embeddings(seurat, "umap"),  font = 2, col = "brown") 
```
# R session information
```{r}
sessionInfo()
```
